apiVersion: v1
kind: Service
metadata:
    name: itop
spec:
    selector:
        app: itop
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          name: http
    type: LoadBalancer
