apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: portainer
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: git@github.com:AlxFrst/k8s-app.git
        targetRevision: HEAD
        path: applications/portainer
        directory:
            recurse: true
    destination:
        server: https://kubernetes.default.svc
        namespace: portainer
    syncPolicy:
        retry:
            limit: 2
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=true
            - Replace=true